import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      zIndex: {
        "floating-element": 5,
        "backdrop": 10,
        "translated-element": 15,
      },
      colors: {
        "on-tertiary-fixed-variant": "#004c6e",
        "surface-tint": "#006398",
        "primary-fixed": "#cce5ff",
        "tertiary-fixed-dim": "#89ceff",
        "surface-container": "#eaedff",
        "on-error": "#ffffff",
        tertiary: "#00628d",
        "outline-variant": "#bfc7d2",
        "on-secondary-fixed-variant": "#003ea8",
        "on-secondary-container": "#fefcff",
        "surface-bright": "#faf8ff",
        primary: "#006194",
        "secondary-container": "#316bf3",
        "surface-variant": "#dae2fd",
        "secondary-fixed-dim": "#b4c5ff",
        "inverse-surface": "#283044",
        "on-tertiary-fixed": "#001e2f",
        outline: "#707881",
        "primary-fixed-dim": "#93ccff",
        "on-secondary": "#ffffff",
        error: "#ba1a1a",
        "surface-container-high": "#e2e7ff",
        surface: "#faf8ff",
        background: "#faf8ff",
        "on-primary-fixed-variant": "#004b73",
        "on-error-container": "#93000a",
        "surface-dim": "#d2d9f4",
        "surface-container-low": "#f2f3ff",
        "primary-container": "#007bb9",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#007cb1",
        "secondary-fixed": "#dbe1ff",
        "inverse-primary": "#93ccff",
        "on-surface-variant": "#3f4850",
        "tertiary-fixed": "#c9e6ff",
        "on-primary-container": "#fdfcff",
        "on-secondary-fixed": "#00174b",
        "on-surface": "#131b2e",
        "on-tertiary-container": "#fcfcff",
        "on-background": "#131b2e",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#001d31",
        "inverse-on-surface": "#eef0ff",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#dae2fd",
        secondary: "#0051d5",
        "on-primary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "gutter-canvas": "0rem",
        "space-xs": "0.25rem",
        "space-xl": "1rem",
        "space-sm": "0.375rem",
        "space-md": "0.5rem",
        margin: "1rem",
        gutter: "0.75rem",
        "space-lg": "0.75rem",
        "space-2xl": "1.5rem",
        "margin-compact": "0.5rem",
      },
      fontFamily: {
        "headline-lg": ["var(--font-hanken-grotesk)", "sans-serif"],
        "label-md": ["var(--font-jetbrains-mono)", "monospace"],
        "body-sm": ["var(--font-hanken-grotesk)", "sans-serif"],
        "label-sm": ["var(--font-jetbrains-mono)", "monospace"],
        "body-md": ["var(--font-hanken-grotesk)", "sans-serif"],
        "label-xs": ["var(--font-jetbrains-mono)", "monospace"],
        "headline-xl": ["var(--font-hanken-grotesk)", "sans-serif"],
        "headline-md": ["var(--font-hanken-grotesk)", "sans-serif"],
        "headline-sm": ["var(--font-hanken-grotesk)", "sans-serif"],
        "body-lg": ["var(--font-hanken-grotesk)", "sans-serif"],
        "label-lg": ["var(--font-jetbrains-mono)", "monospace"],
      },
      fontSize: {
        "headline-lg": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" },
        ],
        "label-md": [
          "11px",
          { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" },
        ],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-sm": [
          "10px",
          { lineHeight: "12px", letterSpacing: "0.04em", fontWeight: "500" },
        ],
        "body-md": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-xs": [
          "9px",
          { lineHeight: "12px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-xl": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "headline-md": [
          "18px",
          { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-sm": [
          "15px",
          { lineHeight: "20px", letterSpacing: "-0.005em", fontWeight: "600" },
        ],
        "body-lg": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "label-lg": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" },
        ],
      },
    },
  },
};

export default config;